### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by efanious** [rahuldange09/Splashy#1]
Please is there a Java version of this library ?

**Comment by rahuldange09** [comment]
No, there is no java version.
But it works properly with java also.
Just add this
`implementation 'com.rbddevs.splashy:splashy:1.1.0'`

**with this (This is important for JAVA only)**
`implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21+" // For JAVA Only`

and it will work just fine.
