### ISSUE TITLE
using java to override onComplete

### ISSUE THREAD

**Issue by brasrox** [rahuldange09/Splashy#2]
hey, can u help me in how i can handle the on complete in java?

// Listener for completion of splash screen
	Splashy.onComplete(object : Splashy.OnComplete {
            override fun onComplete() {
	           Toast.makeText(this@MainActivity, "Logged In", Toast.LENGTH_SHORT).show()
            }

        })

im trying to override it but no sucess =\

**Comment by brasrox** [comment]
class Splashy is final so i cant extends it and try to override it.
How i can override it to use in java?
```
  class s extends Splashy implements Splashy.OnComplete{
    @Override
    public void onComplete() {
      Intent intent = new Intent(this, MainActivity.class);
      startActivity(intent);
      finish();
    }

```

**Comment by rahuldange09** [comment]
Sorry for late reply.
Was busy in work

Here you go

```
Splashy.Companion.onComplete(new Splashy.OnComplete() {
    @Override
    public void onComplete() {
        // Perform action after Splash screen ends
        Toast.makeText(MainActivity.this, "Completed", Toast.LENGTH_SHORT).show();
    }
});
```
