### ISSUE TITLE
Add fun finish to companion?

### ISSUE THREAD

**Issue by kogare** [rahuldange09/Splashy#4]
Hi, I'm using this library for login, but since there's no finish function, it kept coming back to splashy when I click back from main activity. Please consider add finish function.

**Comment by rahuldange09** [comment]
It's already there
`Splashy.Companion.hide();`

**Comment by kogare** [comment]
Yes, but it only hiding, I use it as middle screen from login to main, when I press back it made the app stuck at splashy screen.

**Comment by rahuldange09** [comment]
ohh So it you dont want to go back from main to login at all
you can call Normal Android method
`finishAffinity(); `
It thats not case then let me know
