### ISSUE TITLE
how to hide the splash screen by a click ? (in Java)

### ISSUE THREAD

**Issue by hiwa-jalal** [rahuldange09/Splashy#5]

**Comment by rahuldange09** [comment]
Hello please refer this
https://github.com/rahuldange09/Splashy/issues/3#issuecomment-562890484

**Comment by hiwa-jalal** [comment]
but how can i hide it by clicking on screen for example i have this activity which i show the Splashy Screen in it, and by a click i want the Splashy screen to get hidden.

`public class MainActivity extends AppCompatActivity implements WelcomeFragment.ArrowBtnListener
        , SetupAccountFragment.SetupAccountListener, FoodListFragment.ListenerFoodListFragment {

    FragmentManager fm;
    FlowingDrawer flowingDrawer;
    FrameLayout frameLayout;
    FoodListFragment foodListFragment;
    Map<Integer, Integer> cartValues = new HashMap<>();

    @Override
    public void sendToCart(int value, int adapterPosition) {
        cartValues.put(adapterPosition, value);
        foodListFragment.updateCartValue(getTotalValue());
    }


    private int getTotalValue() {
        int value = 0;
        for (Integer key : cartValues.keySet()) {
            value += cartValues.get(key);
        }
        return value;
    }


    // for account setup fragment

    @Override
    public void btnSignin() {
        fm.beginTransaction()
                .replace(R.id.main_container, new SignInAccountFragment())
                .addToBackStack(null)
                .commit();
    }

    @Override
    public void btnSignup() {
        fm.beginTransaction()
                .replace(R.id.main_container, new SignUpAccountFragment())
                .addToBackStack(null)
                .commit();
    }

    // for account setup fragment


    @Override
    public void onArrowClick() {

        fm.beginTransaction()
                .replace(R.id.main_container, new SetupAccountFragment())
                .addToBackStack(null)
                .commit();
    }
    // for welcome fragment


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        frameLayout = findViewById(R.id.main_container);
        flowingDrawer = findViewById(R.id.drawerlayout);
        flowingDrawer.setTouchMode(ElasticDrawer.TOUCH_MODE_BEZEL);

        Splashy splashy = new Splashy(this);
        splashy.setFullScreen(true)
                .setInfiniteDuration(true)
                .show();

        frameLayout.setOnClickListener(v -> Splashy.Companion.hide());




        fm = getSupportFragmentManager();

        Fragment fragment = fm.findFragmentById(R.id.main_container);

        if (fragment == null) {
            // adding fragment to main container
            fragment = new WelcomeFragment();

            fm.beginTransaction()
                    .replace(R.id.main_container, fragment)
                    .replace(R.id.id_container_menu, new FoodCategoryFragment())
                    .addToBackStack(null)
                    .commit();
        }


    }
}`


activity_main.xml
`<com.mxn.soul.flowingdrawer_core.FlowingDrawer xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/drawerlayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipChildren="false"
    android:clipToPadding="false"
    app:edMenuBackground="#dddddd"
    app:edMenuSize="340dp"
    app:edPosition="2">

    
    <RelativeLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <FrameLayout
            android:id="@+id/main_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />



    </RelativeLayout>

    
    <com.mxn.soul.flowingdrawer_core.FlowingMenuLayout
        android:id="@+id/menulayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <FrameLayout
            android:id="@+id/id_container_menu"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </com.mxn.soul.flowingdrawer_core.FlowingMenuLayout>
</com.mxn.soul.flowingdrawer_core.FlowingDrawer>`

**Comment by rahuldange09** [comment]
Sorry there is not such implementation yet. Will be added in future build

**Comment by hiwa-jalal** [comment]
okay, thanks.

**Comment by rahuldange09** [comment]
Hello,
I have added 
`setClickToHide(true)` method to hide on screen click.
Please update to v1.2.0
