### ISSUE TITLE
How to customize the title and subtitle font?

### ISSUE THREAD

**Issue by DavidErasoGallo** [rahuldange09/Splashy#6]

**Comment by rahuldange09** [comment]
Sorry this feature is not available in this build. Will be added in new release.

**Comment by rahuldange09** [comment]
Added custom font support in v1.2.0.
for Title
`setTitleFontStyle("fonts/satisfy_regular.ttf")`
and
for Subtitle
`setSubTitleFontStyle("fonts/satisfy_regular.ttf")`
Please update to latest version.
