### ISSUE TITLE
Time interval delay frame

### ISSUE THREAD

**Issue by zakblacki** [rahuldange09/Splashy#7]
This thing working good on small project but when I tried on different modules I get few milliseconds main screen displaying before of splash screen unless my code is wrong 

        ` protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         setContentView(R.layout.activity_main);

         //launch splash
         if (!splashLoaded) {
             new Handler().postDelayed(new Runnable() {
                 public void run() {
                    SplashScreen();
                 }
             }, 10);
             splashLoaded = true;
         }

      public void SplashScreen(){
         new Splashy(this)
                 .setLogo(R.drawable.splashy)
                 .setTitle("CaptureDoc")
                 .setSubTitle("Scan Document made easy")
                 .setProgressColor(R.color.black)
                 .setFullScreen(true)
                 .setTime(2500)
                 .setTitleColor(R.color.black)
                 .showTitle(true)
                 .showProgress(true)
                 .setAnimation(Splashy.Animation.GLOW_LOGO_TITLE, 2500)
                 .show();
     }`

**Comment by rahuldange09** [comment]
Hello,
You yourself added runner to show splash after 10ms 
There is no need to add that as setTime() is there.

**Comment by zakblacki** [comment]
> Hello,
> You yourself added runner to show splash after 10ms
even if I put 0 there it won't change 

> There is no need to add that as setTime() is there.
setTime is for how long the splash is displayed

**Comment by rahuldange09** [comment]
Try adding above before
 `setContentView(R.layout.activity_main);`

**Comment by rahuldange09** [comment]
Closing this issue for now.
If you stil facing then fel free to open it.
