### ISSUE TITLE
Hide Not Working

### ISSUE THREAD

**Issue by Pro-Cyborg** [rahuldange09/Splashy#8]
I used it in my Main Activity. In which I check if the user is not equals to null. While I check it I wan't to show the splash screen and it should not get hidden on click. And hence after I check that a user exists then I wan't to hide the splash screen. But the screen does not hides and runs endlessly.

Tell me a way to hide the splash screen!

**Comment by rahuldange09** [comment]
Thanks for opening issue.
Splashy.hide() is fixed now with release 1.3.0
and use setDuration(ms) instead of setTime(ms) (deprecated)
Please update to
`implementation 'com.rbddevs.splashy:splashy:1.3.0'`
