### ISSUE TITLE
Splashy.hide() doesn't work

### ISSUE THREAD

**Issue by hatemdeeb** [rahuldange09/Splashy#9]
Hello!

I am using Java.

When I call Splashy.hide(); I get error ("Cann't resolve method hide()");

Thank you for the good work!

**Comment by rahuldange09** [comment]
Thanks for opening issue.
Splashy.hide() is fixed now with release 1.3.0
and use setDuration(ms) instead of setTime(ms) (deprecated)
Please update to
`implementation 'com.rbddevs.splashy:splashy:1.3.0'`

**Comment by rahuldange09** [comment]
Closing this issue for now.
If you are not agreed, then feel free to reopen it again.
